<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(a,  "\n")

print(int(np.linalg.det(a)), "\n")

print(round((np.linalg.det(a))))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]] 

-13 

-14
