<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Lab_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

X = np.array([[1,1,1], [3,-2,-1],[-1,4,2]], dtype = float)
Y = np.array([[1],[4],[-3]], dtype = float)

print(X, "\n")
print(X.shape, "\n")
print(Y, "\n")
print(Y.shape, "\n")

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]] 

(3, 3) 

[[ 1.]
 [ 4.]
 [-3.]] 

(3, 1) 



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Flour
F = ([[30, 40, 50]])
#Yeast
Y = ([[10, 20, 40]])
#Eggs
E =