<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

A = ([(1, 2, 3), (4, 5, 6)])
B = ([(1,2), (3, 4), (5, 6)])
C = ([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
D = ([(1, 2), (3, 4)])

#AB
print(np.dot(A, B), "\n")

#D+D
print(np.add(D, D), "\n")

#2C
print(np.dot(2, C), "\n")

A = ([2, 7, 4])
B = ([3, 9, 8])

#Cross-Product of A and B
print(np.cross(A, B))

[[22 28]
 [49 64]] 

[[2 4]
 [6 8]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[20 -4 -3]
