<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prelim Exam

Question 1

Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

In [ ]:
import numpy as np

one = ([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
two = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x = np.multiply(one, two)

print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Question 2

In relation to Question 1, show a solution that doubles all the values of each element.

In [ ]:
y = x * 2
print(y)

[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


Question 3

Create a square matrix that has a diagonal 1's.

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question 4

Create a matrix whose elements are:

matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [20]:
import numpy as np

matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(matrix, "\n")

#Size
l = np.size(matrix)
print(l, "\n")

#Shape
m = np.shape(matrix)
print(m, "\n")

n = np.ndim(matrix)
print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

12 

(3, 4) 

2


Question 5

Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [5]:
import numpy as np

arrayOne = np.array([[5,6,9], [21,18,27]])
arrayTwo = np.array([[15,33,24], [4,7,1]])


j = np.add(arrayOne, arrayTwo)

print(j, "\n")

print(j ** 2)


[[20 39 33]
 [25 25 28]] 

[[ 400 1521 1089]
 [ 625  625  784]]
