<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Scaling

In [4]:
import numpy as np

A = np.array([1,5,8,9])
print(A, "\n")

S = 5*A
print(S, "\n")

S = np.multiply(5,A)
S

[1 5 8 9] 

[ 5 25 40 45] 



array([ 5, 25, 40, 45])

Dot Product

In [7]:
a = [5,10,2]
b = [2,4,3]

dotproduct = np.dot(a,b)
print('Dot Product is:', dotproduct)

Dot Product is: 56


Cross Product

In [8]:
p = [4, 2]
q = [5, 6]

product = np.cross(p,q)
print('Cross Product is:', product)

Cross Product is: 14
