<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

A = np.array([[-0.4], [4.3],[-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, -1.5])

print(A, "\n")
print(B,"\n")
print(C, "\n")

sum = np.add(np.add(A, B), C)
diff = np.subtract(np.subtract(A, B), C)
prod = np.multiply(np.multiply(A, B), C)
quo = np.divide(np.divide(A,B), C)

#Multiplication
print("Multiplication:\n", prod, "\n")

#Division
print("Division:\n", quo, "\n")

#Addition
print("Addition:\n", sum, "\n")

#Subtraction
print("Subtraction:\n", diff, "\n")

[[-0.4]
 [ 4.3]
 [-0.6]] 

[-0.2  0.2  1. ] 

[-0.2  2.1 -1.5] 

Multiplication:
 [[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]] 

Division:
 [[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]] 

Addition:
 [[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]] 

Subtraction:
 [[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]] 

