<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Lab_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([[1,4], [0,3]])

round(np.linalg.det(A))

3

In [8]:
B = np.array([[1,3,5, 6], [0,3,1,3], [3,1,8,2], [5,2,6,8]])

round(np.linalg.det(B))

-235

#Coding Activity 9

In [9]:
x = np.array([[1,2,3],[2,3,1],[3,1,2]])
y = np.array([[4,5,6],[5,6,4],[6,4,5]])
z = np.array([[7,8,9],[8,9,7],[9,7,8]])

print(x)
print(y)
print(z)

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[[4 5 6]
 [5 6 4]
 [6 4 5]]
[[7 8 9]
 [8 9 7]
 [9 7 8]]


Associative Property: (AB)C = A(BC)

In [10]:
#(AB)C
print(np.dot(np.dot(x,y), z),"\n")
#A(BC)
print(np.dot(np.dot(y,z), x))

[[717 720 723]
 [720 723 717]
 [723 717 720]] 

[[717 720 723]
 [720 723 717]
 [723 717 720]]


Distributive Property: A(B + C) = AB + AC

In [11]:
#A(B+C)
print(np.dot(np.add(y,z), x))

#AB + AC
a = np.dot(x,y)
b = np.dot(x,z)

print("\n", np.add(a,b))

[[82 76 76]
 [76 82 76]
 [76 76 82]]

 [[82 76 76]
 [76 82 76]
 [76 76 82]]


Closure Property: c(x)

In [12]:
c = 2
print(np.dot(c,x))

[[2 4 6]
 [4 6 2]
 [6 2 4]]


Identity Property

In [21]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Zero/Null Property

In [22]:
print(np.zeros([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Scalar Property

In [23]:
e = 2
print(np.dot(e, np.eye(3,3)))

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
