<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vector Operations**

**Vector Addition**

In [34]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(A + B + C)

#OR

print(np.add(A, np.add(B,C)), "\n")

np.sum(B)

[ 4  3 -1]
[ 4  3 -1] 



2

In [36]:
#Testing other methods

print(np.sum(A))
print(np.sum(B))
print(np.sum(C),"\n")

print(np.sum(A + B + C)) #Summation of the matrix


3
2
1 

6


**Vector Subtraction**

In [26]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(np.subtract(A, B))

#OR

print(A - B)

[-2  1  2]
[-2  1  2]


**Vector Multiplication**

In [38]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(np.multiply(A,B))

#OR

print(A * B)

[3 2 0]
[3 2 0]


**Vector Division**

In [52]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(np.divide(A,B))

#OR

print(A / B)

C = np.array([3.9, 1.8, 7.7])
D = np.array([1, 1, 1])

print(C // D)

print(np.array(A/B, dtype=int))

[ 0.33333333  2.         -0.        ]
[ 0.33333333  2.         -0.        ]
[3. 1. 7.]
[0 2 0]
