<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Python_Exercise_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrices

In [8]:
#Function to  describe matrix
import numpy as np

def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:{matrix.shape}\nRank:{matrix.ndim}\n')

In [10]:
#Declaring a 2x2 matrix
A = np.array([[1,2],[3,1]])

describe_mat(A)

G = np.array([[1,1],[2,2]])

describe_mat(G)

Matrix:
[[1 2]
 [3 1]]

Shape:(2, 2)
Rank:2

Matrix:
[[1 1]
 [2 2]]

Shape:(2, 2)
Rank:2



In [11]:
#Declaring  a 3x2 matrix
B = np.array([[8,2],[5,4],[1,1]])

describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:(3, 2)
Rank:2



In [17]:
H = np.array([1,2,3,4,5])

describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:(5,)
Rank:1

