<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

X = np.array([[1,1,1], [3,-2,-1],[-1,4,2]], dtype = float)
Y = np.array([[1],[4],[-3]], dtype = float)

print(X, "\n")
print(X.shape, "\n")
print(Y, "\n")
print(Y.shape, "\n")

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]] 

(3, 3) 

[[ 1.]
 [ 4.]
 [-3.]] 

(3, 1) 



In [3]:
import numpy as np

#Formula
#F is flour, Y is yeast, E is eggs

#30F + 10Y + 120E = 12500
#40F + 20Y + 200E = 18000
#50F + 40Y + 360E = 25700

#Array for Coefficients
ingredients = np.array([[30,10,120],[40,20,200],[50,40,360]])

#Array for Prices
prices = np.array([12500, 18000, 25700])

#solving for the equations
sol = np.linalg.solve(ingredients, prices)

#extract the prices from the solution
flour, yeast, egg =  sol

fps = str(round(flour, 2))
yps = str(round(yeast, 2))
eps = str(round(egg, 2))

print(ingredients, "\n")
print(prices, "\n")
print("Price of flour per sack: " + fps + " pesos")
print("Price of yeast per pack: " + yps + " pesos")
print("Price of one piece of egg: " + eps + " pesos")

[[ 30  10 120]
 [ 40  20 200]
 [ 50  40 360]] 

[12500 18000 25700] 

Price of flour per sack: 330.0 pesos
Price of yeast per pack: 140.0 pesos
Price of one piece of egg: 10.0 pesos
