<a href="https://colab.research.google.com/github/jamesdayao/58013-Linear-Algebra/blob/main/Vector%2C_Spaces%2C_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy; Vectors and Operations

In [ ]:
import numpy as np #np here is a variable name

A = np.array([4,3]) #A here represents 1 matrix
B = np.array([2, -5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Size Dimention, Sizae


In [ ]:
#Column
import numpy as np

ball1 = np.array([[1],[2],[3]])
ball2 = np.array([0,1,-1])

print(ball1)


[[1]
 [2]
 [3]]


In [ ]:
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

print(ball1)
print(ball2)

x = np.shape(ball1)
y = np.shape(ball2)
z = (x + y)

print(z)

q = np.ndim(x)
w = np.ndim(y)

print(q)
print(w)


[1 2 3]
[ 0  1 -1]
(3, 3)
1
1


Operations of Vector Spaces

In [74]:
#Addition
import numpy as np

A = np.array([4, 3])
B = np.array([2,-5])

R1 = A + B
R2 = np.add(A, B)
print(R1, R2)

[ 6 -2] [ 6 -2]


In [75]:
#Subtraction

import numpy as np
A = np.array([4, 3])
B = np.array([2,-5])

R1 = A - B
R2 = np.subtract(A, B)
print(R1, R2)
R3 = np.subtract(B, A)
print(R3)

[2 8] [2 8]
[-2 -8]


In [76]:
#Multiplication

import numpy as np

A = np.array([4, 3])
B = np.array([2,-5])

R1 = A * B
R2 = np.multiply(A, B)
print(R1, R2)

[  8 -15] [  8 -15]


In [80]:
#Scalar
import numpy as np

A = np.array([4, 3])
B = np.array([2,-5])

S = np.array([2])
T = S*A

print(T)

[8 6]


In [105]:
#Dot Product
import numpy as np

A = np.array([4, 3])
B = np.array([2,-5])

B = B.reshape(2,1)
C = np.multiply(A,B)
print(C)

[[  8   6]
 [-20 -15]]


Matrix Property

In [88]:
#Identity Matrix
import numpy as np

c = np.eye(3,3)
print(c)

#All diagonals are 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [89]:
#Zero Matrix

d = np.zeros([5,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [98]:
#Full Matrix

e = np.full((3,3), 69)
print(e)

[[69 69 69]
 [69 69 69]
 [69 69 69]]


In [106]:
#Transpose Matrix

f = np.transpose(C)
print(f)

[[  8 -20]
 [  6 -15]]
